main: water.of.cup.boardgames.BoardGames
name: ChessBoards
version: '1.2.10'
description: Adds chess games to Minecraft.
author: Nicholas Kopiwoda & Matt C.
api-version: 1.16
softdepends: [Vault, PlaceholderAPI]
commands:
  chessboards:
    description: All commands for the ChessBoards plugin.
    aliases: [cb]