main: water.of.cup.boardgames.BoardGames
name: BoardGames
version: '1.1.0'
description: Adds board games to Minecraft.
author: Nicholas Kopiwoda, Matt C. & WordSmith123
api-version: 1.18
softdepend: [Vault, PlaceholderAPI, Citizens]
commands:
  bg:
    description: All commands for the BoardGames plugin.
    aliases: [bg]
